// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bundled_services.proto

package furo_type

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type GetPersonServiceRequest struct {
	Prs                  string   `protobuf:"bytes,1,opt,name=prs,proto3" json:"prs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPersonServiceRequest) Reset()         { *m = GetPersonServiceRequest{} }
func (m *GetPersonServiceRequest) String() string { return proto.CompactTextString(m) }
func (*GetPersonServiceRequest) ProtoMessage()    {}
func (*GetPersonServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bundled_services_0ca539621d5855d4, []int{0}
}
func (m *GetPersonServiceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetPersonServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetPersonServiceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *GetPersonServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPersonServiceRequest.Merge(dst, src)
}
func (m *GetPersonServiceRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetPersonServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPersonServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPersonServiceRequest proto.InternalMessageInfo

func (m *GetPersonServiceRequest) GetPrs() string {
	if m != nil {
		return m.Prs
	}
	return ""
}

type ListPersonServiceRequest struct {
	// Partielle Repräsentation fields=id,name // 10
	Fields string `protobuf:"bytes,1,opt,name=fields,proto3" json:"fields,omitempty"`
	// Sortierung nach feldern
	// **?filter=-completed** um completed absteigend zu bekommen
	// **?filter=completed** um completed aufsteigend zu bekommen
	Sort string `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	// Filter
	Filter string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	// Gewünschte Seite. Tipp: Folge dem HATEOAS next, prev,...
	Page int32 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	// Anzahl Elemente pro Seite, maximal sind 99 erlaubt
	Limit int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	// Meta für die Anzahl der Elemente der Resource, bei true ist in der Antwort Meta der count aufgeführt
	Count bool `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	// not implemented
	Sum string `protobuf:"bytes,7,opt,name=sum,proto3" json:"sum,omitempty"`
	// not implemented (ehemals context)
	View string `protobuf:"bytes,8,opt,name=view,proto3" json:"view,omitempty"`
	// Query term to search a member
	Q                    string   `protobuf:"bytes,11,opt,name=q,proto3" json:"q,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPersonServiceRequest) Reset()         { *m = ListPersonServiceRequest{} }
func (m *ListPersonServiceRequest) String() string { return proto.CompactTextString(m) }
func (*ListPersonServiceRequest) ProtoMessage()    {}
func (*ListPersonServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bundled_services_0ca539621d5855d4, []int{1}
}
func (m *ListPersonServiceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListPersonServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListPersonServiceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ListPersonServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPersonServiceRequest.Merge(dst, src)
}
func (m *ListPersonServiceRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListPersonServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPersonServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPersonServiceRequest proto.InternalMessageInfo

func (m *ListPersonServiceRequest) GetFields() string {
	if m != nil {
		return m.Fields
	}
	return ""
}

func (m *ListPersonServiceRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *ListPersonServiceRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ListPersonServiceRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListPersonServiceRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListPersonServiceRequest) GetCount() bool {
	if m != nil {
		return m.Count
	}
	return false
}

func (m *ListPersonServiceRequest) GetSum() string {
	if m != nil {
		return m.Sum
	}
	return ""
}

func (m *ListPersonServiceRequest) GetView() string {
	if m != nil {
		return m.View
	}
	return ""
}

func (m *ListPersonServiceRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

type ListServiceProjectMembersRequest struct {
	// Partielle Repräsentation fields=id,name // 10
	Fields string `protobuf:"bytes,1,opt,name=fields,proto3" json:"fields,omitempty"`
	// Sortierung nach feldern
	// **?filter=-completed** um completed absteigend zu bekommen
	// **?filter=completed** um completed aufsteigend zu bekommen
	Sort string `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	// Filter
	Filter string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	// Gewünschte Seite. Tipp: Folge dem HATEOAS next, prev,...
	Page int32 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	// Anzahl Elemente pro Seite, maximal sind 99 erlaubt
	Limit int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	// Meta für die Anzahl der Elemente der Resource, bei true ist in der Antwort Meta der count aufgeführt
	Count bool `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	// not implemented
	Sum string `protobuf:"bytes,7,opt,name=sum,proto3" json:"sum,omitempty"`
	// not implemented (ehemals context)
	View string `protobuf:"bytes,8,opt,name=view,proto3" json:"view,omitempty"`
	// Query term to search a member
	Q                    string   `protobuf:"bytes,11,opt,name=q,proto3" json:"q,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListServiceProjectMembersRequest) Reset()         { *m = ListServiceProjectMembersRequest{} }
func (m *ListServiceProjectMembersRequest) String() string { return proto.CompactTextString(m) }
func (*ListServiceProjectMembersRequest) ProtoMessage()    {}
func (*ListServiceProjectMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bundled_services_0ca539621d5855d4, []int{2}
}
func (m *ListServiceProjectMembersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListServiceProjectMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListServiceProjectMembersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ListServiceProjectMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServiceProjectMembersRequest.Merge(dst, src)
}
func (m *ListServiceProjectMembersRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListServiceProjectMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServiceProjectMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListServiceProjectMembersRequest proto.InternalMessageInfo

func (m *ListServiceProjectMembersRequest) GetFields() string {
	if m != nil {
		return m.Fields
	}
	return ""
}

func (m *ListServiceProjectMembersRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *ListServiceProjectMembersRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ListServiceProjectMembersRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListServiceProjectMembersRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListServiceProjectMembersRequest) GetCount() bool {
	if m != nil {
		return m.Count
	}
	return false
}

func (m *ListServiceProjectMembersRequest) GetSum() string {
	if m != nil {
		return m.Sum
	}
	return ""
}

func (m *ListServiceProjectMembersRequest) GetView() string {
	if m != nil {
		return m.View
	}
	return ""
}

func (m *ListServiceProjectMembersRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

type UnsubscribeServiceProjectMembersRequest struct {
	Prs                  string        `protobuf:"bytes,1,opt,name=prs,proto3" json:"prs,omitempty"`
	Data                 *PersonEntity `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UnsubscribeServiceProjectMembersRequest) Reset() {
	*m = UnsubscribeServiceProjectMembersRequest{}
}
func (m *UnsubscribeServiceProjectMembersRequest) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeServiceProjectMembersRequest) ProtoMessage()    {}
func (*UnsubscribeServiceProjectMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bundled_services_0ca539621d5855d4, []int{3}
}
func (m *UnsubscribeServiceProjectMembersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UnsubscribeServiceProjectMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UnsubscribeServiceProjectMembersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *UnsubscribeServiceProjectMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsubscribeServiceProjectMembersRequest.Merge(dst, src)
}
func (m *UnsubscribeServiceProjectMembersRequest) XXX_Size() int {
	return m.Size()
}
func (m *UnsubscribeServiceProjectMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsubscribeServiceProjectMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnsubscribeServiceProjectMembersRequest proto.InternalMessageInfo

func (m *UnsubscribeServiceProjectMembersRequest) GetPrs() string {
	if m != nil {
		return m.Prs
	}
	return ""
}

func (m *UnsubscribeServiceProjectMembersRequest) GetData() *PersonEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*GetPersonServiceRequest)(nil), "furo.type.GetPersonServiceRequest")
	proto.RegisterType((*ListPersonServiceRequest)(nil), "furo.type.ListPersonServiceRequest")
	proto.RegisterType((*ListServiceProjectMembersRequest)(nil), "furo.type.ListServiceProjectMembersRequest")
	proto.RegisterType((*UnsubscribeServiceProjectMembersRequest)(nil), "furo.type.UnsubscribeServiceProjectMembersRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProjectServiceClient is the client API for ProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProjectServiceClient interface {
}

type projectServiceClient struct {
	cc *grpc.ClientConn
}

func NewProjectServiceClient(cc *grpc.ClientConn) ProjectServiceClient {
	return &projectServiceClient{cc}
}

// ProjectServiceServer is the server API for ProjectService service.
type ProjectServiceServer interface {
}

func RegisterProjectServiceServer(s *grpc.Server, srv ProjectServiceServer) {
	s.RegisterService(&_ProjectService_serviceDesc, srv)
}

var _ProjectService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "furo.type.ProjectService",
	HandlerType: (*ProjectServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "bundled_services.proto",
}

// PersonServiceServiceClient is the client API for PersonServiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonServiceServiceClient interface {
	// Get a PersonEntity
	GetPersonService(ctx context.Context, in *GetPersonServiceRequest, opts ...grpc.CallOption) (*PersonEntity, error)
	// Get a collection with PersonEntities
	ListPersonService(ctx context.Context, in *ListPersonServiceRequest, opts ...grpc.CallOption) (*PersonCollection, error)
}

type personServiceServiceClient struct {
	cc *grpc.ClientConn
}

func NewPersonServiceServiceClient(cc *grpc.ClientConn) PersonServiceServiceClient {
	return &personServiceServiceClient{cc}
}

func (c *personServiceServiceClient) GetPersonService(ctx context.Context, in *GetPersonServiceRequest, opts ...grpc.CallOption) (*PersonEntity, error) {
	out := new(PersonEntity)
	err := c.cc.Invoke(ctx, "/furo.type.PersonServiceService/GetPersonService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personServiceServiceClient) ListPersonService(ctx context.Context, in *ListPersonServiceRequest, opts ...grpc.CallOption) (*PersonCollection, error) {
	out := new(PersonCollection)
	err := c.cc.Invoke(ctx, "/furo.type.PersonServiceService/ListPersonService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonServiceServiceServer is the server API for PersonServiceService service.
type PersonServiceServiceServer interface {
	// Get a PersonEntity
	GetPersonService(context.Context, *GetPersonServiceRequest) (*PersonEntity, error)
	// Get a collection with PersonEntities
	ListPersonService(context.Context, *ListPersonServiceRequest) (*PersonCollection, error)
}

func RegisterPersonServiceServiceServer(s *grpc.Server, srv PersonServiceServiceServer) {
	s.RegisterService(&_PersonServiceService_serviceDesc, srv)
}

func _PersonServiceService_GetPersonService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersonServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServiceServer).GetPersonService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/furo.type.PersonServiceService/GetPersonService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServiceServer).GetPersonService(ctx, req.(*GetPersonServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonServiceService_ListPersonService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPersonServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServiceServer).ListPersonService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/furo.type.PersonServiceService/ListPersonService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServiceServer).ListPersonService(ctx, req.(*ListPersonServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonServiceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "furo.type.PersonServiceService",
	HandlerType: (*PersonServiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPersonService",
			Handler:    _PersonServiceService_GetPersonService_Handler,
		},
		{
			MethodName: "ListPersonService",
			Handler:    _PersonServiceService_ListPersonService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bundled_services.proto",
}

// ProjectTaskServiceClient is the client API for ProjectTaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProjectTaskServiceClient interface {
}

type projectTaskServiceClient struct {
	cc *grpc.ClientConn
}

func NewProjectTaskServiceClient(cc *grpc.ClientConn) ProjectTaskServiceClient {
	return &projectTaskServiceClient{cc}
}

// ProjectTaskServiceServer is the server API for ProjectTaskService service.
type ProjectTaskServiceServer interface {
}

func RegisterProjectTaskServiceServer(s *grpc.Server, srv ProjectTaskServiceServer) {
	s.RegisterService(&_ProjectTaskService_serviceDesc, srv)
}

var _ProjectTaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "furo.type.ProjectTaskService",
	HandlerType: (*ProjectTaskServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "bundled_services.proto",
}

// ProjectTreeServiceClient is the client API for ProjectTreeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProjectTreeServiceClient interface {
}

type projectTreeServiceClient struct {
	cc *grpc.ClientConn
}

func NewProjectTreeServiceClient(cc *grpc.ClientConn) ProjectTreeServiceClient {
	return &projectTreeServiceClient{cc}
}

// ProjectTreeServiceServer is the server API for ProjectTreeService service.
type ProjectTreeServiceServer interface {
}

func RegisterProjectTreeServiceServer(s *grpc.Server, srv ProjectTreeServiceServer) {
	s.RegisterService(&_ProjectTreeService_serviceDesc, srv)
}

var _ProjectTreeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "furo.type.ProjectTreeService",
	HandlerType: (*ProjectTreeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "bundled_services.proto",
}

// ServiceProjectMembersServiceClient is the client API for ServiceProjectMembersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceProjectMembersServiceClient interface {
	// Get a collection with PersonEntities
	ListServiceProjectMembers(ctx context.Context, in *ListServiceProjectMembersRequest, opts ...grpc.CallOption) (*PersonCollection, error)
	// Custom method to unsubscribe a member, complete PersonEntity is expected
	UnsubscribeServiceProjectMembers(ctx context.Context, in *UnsubscribeServiceProjectMembersRequest, opts ...grpc.CallOption) (*PersonCollection, error)
}

type serviceProjectMembersServiceClient struct {
	cc *grpc.ClientConn
}

func NewServiceProjectMembersServiceClient(cc *grpc.ClientConn) ServiceProjectMembersServiceClient {
	return &serviceProjectMembersServiceClient{cc}
}

func (c *serviceProjectMembersServiceClient) ListServiceProjectMembers(ctx context.Context, in *ListServiceProjectMembersRequest, opts ...grpc.CallOption) (*PersonCollection, error) {
	out := new(PersonCollection)
	err := c.cc.Invoke(ctx, "/furo.type.ServiceProjectMembersService/ListServiceProjectMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceProjectMembersServiceClient) UnsubscribeServiceProjectMembers(ctx context.Context, in *UnsubscribeServiceProjectMembersRequest, opts ...grpc.CallOption) (*PersonCollection, error) {
	out := new(PersonCollection)
	err := c.cc.Invoke(ctx, "/furo.type.ServiceProjectMembersService/UnsubscribeServiceProjectMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceProjectMembersServiceServer is the server API for ServiceProjectMembersService service.
type ServiceProjectMembersServiceServer interface {
	// Get a collection with PersonEntities
	ListServiceProjectMembers(context.Context, *ListServiceProjectMembersRequest) (*PersonCollection, error)
	// Custom method to unsubscribe a member, complete PersonEntity is expected
	UnsubscribeServiceProjectMembers(context.Context, *UnsubscribeServiceProjectMembersRequest) (*PersonCollection, error)
}

func RegisterServiceProjectMembersServiceServer(s *grpc.Server, srv ServiceProjectMembersServiceServer) {
	s.RegisterService(&_ServiceProjectMembersService_serviceDesc, srv)
}

func _ServiceProjectMembersService_ListServiceProjectMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServiceProjectMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceProjectMembersServiceServer).ListServiceProjectMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/furo.type.ServiceProjectMembersService/ListServiceProjectMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceProjectMembersServiceServer).ListServiceProjectMembers(ctx, req.(*ListServiceProjectMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceProjectMembersService_UnsubscribeServiceProjectMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeServiceProjectMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceProjectMembersServiceServer).UnsubscribeServiceProjectMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/furo.type.ServiceProjectMembersService/UnsubscribeServiceProjectMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceProjectMembersServiceServer).UnsubscribeServiceProjectMembers(ctx, req.(*UnsubscribeServiceProjectMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceProjectMembersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "furo.type.ServiceProjectMembersService",
	HandlerType: (*ServiceProjectMembersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListServiceProjectMembers",
			Handler:    _ServiceProjectMembersService_ListServiceProjectMembers_Handler,
		},
		{
			MethodName: "UnsubscribeServiceProjectMembers",
			Handler:    _ServiceProjectMembersService_UnsubscribeServiceProjectMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bundled_services.proto",
}

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskServiceClient interface {
}

type taskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskServiceClient(cc *grpc.ClientConn) TaskServiceClient {
	return &taskServiceClient{cc}
}

// TaskServiceServer is the server API for TaskService service.
type TaskServiceServer interface {
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "furo.type.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "bundled_services.proto",
}

func (m *GetPersonServiceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetPersonServiceRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Prs) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintBundledServices(dAtA, i, uint64(len(m.Prs)))
		i += copy(dAtA[i:], m.Prs)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ListPersonServiceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListPersonServiceRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Fields) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintBundledServices(dAtA, i, uint64(len(m.Fields)))
		i += copy(dAtA[i:], m.Fields)
	}
	if len(m.Sort) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintBundledServices(dAtA, i, uint64(len(m.Sort)))
		i += copy(dAtA[i:], m.Sort)
	}
	if len(m.Filter) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintBundledServices(dAtA, i, uint64(len(m.Filter)))
		i += copy(dAtA[i:], m.Filter)
	}
	if m.Page != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintBundledServices(dAtA, i, uint64(m.Page))
	}
	if m.Limit != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintBundledServices(dAtA, i, uint64(m.Limit))
	}
	if m.Count {
		dAtA[i] = 0x30
		i++
		if m.Count {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.Sum) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintBundledServices(dAtA, i, uint64(len(m.Sum)))
		i += copy(dAtA[i:], m.Sum)
	}
	if len(m.View) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintBundledServices(dAtA, i, uint64(len(m.View)))
		i += copy(dAtA[i:], m.View)
	}
	if len(m.Q) > 0 {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintBundledServices(dAtA, i, uint64(len(m.Q)))
		i += copy(dAtA[i:], m.Q)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ListServiceProjectMembersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListServiceProjectMembersRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Fields) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintBundledServices(dAtA, i, uint64(len(m.Fields)))
		i += copy(dAtA[i:], m.Fields)
	}
	if len(m.Sort) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintBundledServices(dAtA, i, uint64(len(m.Sort)))
		i += copy(dAtA[i:], m.Sort)
	}
	if len(m.Filter) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintBundledServices(dAtA, i, uint64(len(m.Filter)))
		i += copy(dAtA[i:], m.Filter)
	}
	if m.Page != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintBundledServices(dAtA, i, uint64(m.Page))
	}
	if m.Limit != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintBundledServices(dAtA, i, uint64(m.Limit))
	}
	if m.Count {
		dAtA[i] = 0x30
		i++
		if m.Count {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.Sum) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintBundledServices(dAtA, i, uint64(len(m.Sum)))
		i += copy(dAtA[i:], m.Sum)
	}
	if len(m.View) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintBundledServices(dAtA, i, uint64(len(m.View)))
		i += copy(dAtA[i:], m.View)
	}
	if len(m.Q) > 0 {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintBundledServices(dAtA, i, uint64(len(m.Q)))
		i += copy(dAtA[i:], m.Q)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *UnsubscribeServiceProjectMembersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UnsubscribeServiceProjectMembersRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Prs) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintBundledServices(dAtA, i, uint64(len(m.Prs)))
		i += copy(dAtA[i:], m.Prs)
	}
	if m.Data != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintBundledServices(dAtA, i, uint64(m.Data.Size()))
		n1, err := m.Data.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintBundledServices(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *GetPersonServiceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Prs)
	if l > 0 {
		n += 1 + l + sovBundledServices(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ListPersonServiceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Fields)
	if l > 0 {
		n += 1 + l + sovBundledServices(uint64(l))
	}
	l = len(m.Sort)
	if l > 0 {
		n += 1 + l + sovBundledServices(uint64(l))
	}
	l = len(m.Filter)
	if l > 0 {
		n += 1 + l + sovBundledServices(uint64(l))
	}
	if m.Page != 0 {
		n += 1 + sovBundledServices(uint64(m.Page))
	}
	if m.Limit != 0 {
		n += 1 + sovBundledServices(uint64(m.Limit))
	}
	if m.Count {
		n += 2
	}
	l = len(m.Sum)
	if l > 0 {
		n += 1 + l + sovBundledServices(uint64(l))
	}
	l = len(m.View)
	if l > 0 {
		n += 1 + l + sovBundledServices(uint64(l))
	}
	l = len(m.Q)
	if l > 0 {
		n += 1 + l + sovBundledServices(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ListServiceProjectMembersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Fields)
	if l > 0 {
		n += 1 + l + sovBundledServices(uint64(l))
	}
	l = len(m.Sort)
	if l > 0 {
		n += 1 + l + sovBundledServices(uint64(l))
	}
	l = len(m.Filter)
	if l > 0 {
		n += 1 + l + sovBundledServices(uint64(l))
	}
	if m.Page != 0 {
		n += 1 + sovBundledServices(uint64(m.Page))
	}
	if m.Limit != 0 {
		n += 1 + sovBundledServices(uint64(m.Limit))
	}
	if m.Count {
		n += 2
	}
	l = len(m.Sum)
	if l > 0 {
		n += 1 + l + sovBundledServices(uint64(l))
	}
	l = len(m.View)
	if l > 0 {
		n += 1 + l + sovBundledServices(uint64(l))
	}
	l = len(m.Q)
	if l > 0 {
		n += 1 + l + sovBundledServices(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *UnsubscribeServiceProjectMembersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Prs)
	if l > 0 {
		n += 1 + l + sovBundledServices(uint64(l))
	}
	if m.Data != nil {
		l = m.Data.Size()
		n += 1 + l + sovBundledServices(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovBundledServices(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozBundledServices(x uint64) (n int) {
	return sovBundledServices(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GetPersonServiceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBundledServices
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetPersonServiceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetPersonServiceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundledServices
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Prs = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBundledServices(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBundledServices
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListPersonServiceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBundledServices
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListPersonServiceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListPersonServiceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fields", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundledServices
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fields = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sort", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundledServices
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sort = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundledServices
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Filter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			m.Page = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Page |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Count = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundledServices
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sum = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field View", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundledServices
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.View = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Q", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundledServices
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Q = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBundledServices(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBundledServices
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListServiceProjectMembersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBundledServices
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListServiceProjectMembersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListServiceProjectMembersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fields", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundledServices
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fields = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sort", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundledServices
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sort = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundledServices
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Filter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			m.Page = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Page |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Count = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundledServices
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sum = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field View", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundledServices
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.View = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Q", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundledServices
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Q = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBundledServices(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBundledServices
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UnsubscribeServiceProjectMembersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBundledServices
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UnsubscribeServiceProjectMembersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UnsubscribeServiceProjectMembersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBundledServices
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Prs = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBundledServices
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Data == nil {
				m.Data = &PersonEntity{}
			}
			if err := m.Data.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBundledServices(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBundledServices
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBundledServices(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBundledServices
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBundledServices
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthBundledServices
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowBundledServices
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipBundledServices(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthBundledServices = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBundledServices   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("bundled_services.proto", fileDescriptor_bundled_services_0ca539621d5855d4)
}

var fileDescriptor_bundled_services_0ca539621d5855d4 = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xd5, 0xa6, 0x49, 0x68, 0x27, 0xa1, 0x0a, 0xab, 0xa8, 0x5d, 0x4c, 0x15, 0x59, 0x46, 0x82,
	0x48, 0x41, 0x89, 0x64, 0x6e, 0x3d, 0x82, 0x10, 0x17, 0x90, 0x2a, 0x03, 0x67, 0x64, 0x3b, 0xd3,
	0xb0, 0xc4, 0xf6, 0x3a, 0xbb, 0xeb, 0xa2, 0xaa, 0xe2, 0xc2, 0x2f, 0xf0, 0x05, 0x7c, 0x09, 0x57,
	0x8e, 0x08, 0x6e, 0x9c, 0x50, 0xc4, 0x07, 0xf0, 0x09, 0xc8, 0x6b, 0xbb, 0x98, 0xa6, 0x09, 0x70,
	0xec, 0x29, 0x33, 0x93, 0xf1, 0x9b, 0xf7, 0x66, 0x9e, 0x0d, 0x7b, 0x41, 0x96, 0x4c, 0x23, 0x9c,
	0xbe, 0x54, 0x28, 0x4f, 0x78, 0x88, 0x6a, 0x9c, 0x4a, 0xa1, 0x05, 0xdd, 0x39, 0xce, 0xa4, 0x18,
	0xeb, 0xd3, 0x14, 0xad, 0x83, 0x99, 0x10, 0xb3, 0x08, 0x27, 0x7e, 0xca, 0x27, 0x7e, 0x92, 0x08,
	0xed, 0x6b, 0x2e, 0x92, 0xb2, 0xd1, 0x3a, 0x07, 0x88, 0x51, 0x29, 0x7f, 0x56, 0x01, 0x38, 0x23,
	0xd8, 0x7f, 0x8c, 0xfa, 0x08, 0xa5, 0x12, 0xc9, 0xb3, 0x02, 0xdb, 0xc3, 0x45, 0x86, 0x4a, 0xd3,
	0x1e, 0x6c, 0xa5, 0x52, 0x31, 0x62, 0x93, 0xe1, 0x8e, 0x97, 0x87, 0xce, 0x17, 0x02, 0xec, 0x09,
	0x57, 0x97, 0xb7, 0xef, 0x41, 0xfb, 0x98, 0x63, 0x34, 0xad, 0x9e, 0x28, 0x33, 0x4a, 0xa1, 0xa9,
	0x84, 0xd4, 0xac, 0x61, 0xaa, 0x26, 0x2e, 0x7a, 0x23, 0x8d, 0x92, 0x6d, 0x55, 0xbd, 0x79, 0x96,
	0xf7, 0xa6, 0xfe, 0x0c, 0x59, 0xd3, 0x26, 0xc3, 0x96, 0x67, 0x62, 0xda, 0x87, 0x56, 0xc4, 0x63,
	0xae, 0x59, 0xcb, 0x14, 0x8b, 0x24, 0xaf, 0x86, 0x22, 0x4b, 0x34, 0x6b, 0xdb, 0x64, 0xb8, 0xed,
	0x15, 0x49, 0x4e, 0x59, 0x65, 0x31, 0xbb, 0x56, 0x50, 0x56, 0x59, 0x9c, 0x23, 0x9e, 0x70, 0x7c,
	0xc3, 0xb6, 0x8b, 0xe9, 0x79, 0x4c, 0xbb, 0x40, 0x16, 0xac, 0x63, 0x0a, 0x64, 0xe1, 0x7c, 0x23,
	0x60, 0xe7, 0xa2, 0x4a, 0x39, 0x47, 0x52, 0xbc, 0xc6, 0x50, 0x3f, 0xc5, 0x38, 0x40, 0xa9, 0xae,
	0xba, 0xb8, 0x57, 0x70, 0xf7, 0x45, 0xa2, 0xb2, 0x40, 0x85, 0x92, 0x07, 0xb8, 0x51, 0xe2, 0xca,
	0xb9, 0xe9, 0x08, 0x9a, 0x53, 0x5f, 0xfb, 0x46, 0x5c, 0xc7, 0xdd, 0x1f, 0x9f, 0x7b, 0x6d, 0x5c,
	0x18, 0xe0, 0x51, 0xa2, 0xb9, 0x3e, 0xf5, 0x4c, 0x93, 0xdb, 0x83, 0xdd, 0x12, 0xb7, 0x9c, 0xe2,
	0xfe, 0x24, 0xd0, 0xff, 0xc3, 0x29, 0xe5, 0x0f, 0x9d, 0x43, 0xef, 0xa2, 0xe7, 0xa8, 0x53, 0x43,
	0x5f, 0x63, 0x48, 0x6b, 0x1d, 0x03, 0xc7, 0x7a, 0xf7, 0xf5, 0xc7, 0xfb, 0x46, 0x9f, 0x52, 0x63,
	0xfe, 0xd4, 0xfc, 0xa5, 0x26, 0x67, 0xa9, 0x54, 0x6f, 0xe9, 0x1c, 0x6e, 0xac, 0x58, 0x96, 0xde,
	0xae, 0x21, 0xad, 0x33, 0xb4, 0x75, 0x6b, 0x65, 0xdc, 0x43, 0x11, 0x45, 0x18, 0xe6, 0xaf, 0x95,
	0xd3, 0x37, 0x23, 0x77, 0x69, 0xb7, 0x3e, 0xd2, 0xed, 0x03, 0x2d, 0x97, 0xf0, 0xdc, 0x57, 0xf3,
	0x6a, 0x11, 0xb5, 0xaa, 0xc4, 0x6a, 0x0b, 0xee, 0xc7, 0x06, 0x1c, 0x5c, 0x7a, 0x90, 0x8a, 0xe4,
	0x19, 0xdc, 0x5c, 0xeb, 0x4b, 0x3a, 0xba, 0xa0, 0x60, 0xd3, 0x69, 0xff, 0x47, 0x49, 0x5c, 0xe2,
	0x7f, 0x20, 0x60, 0xff, 0xcd, 0x39, 0xd4, 0xad, 0xe1, 0xfe, 0xa3, 0xcd, 0x36, 0x73, 0xb9, 0x67,
	0xb8, 0xdc, 0x71, 0x06, 0x75, 0x2e, 0xc5, 0x21, 0x0f, 0xb3, 0xdf, 0x03, 0x0e, 0x0b, 0xcb, 0x5d,
	0x87, 0x4e, 0x6d, 0xcd, 0x0f, 0xba, 0x9f, 0x96, 0x03, 0xf2, 0x79, 0x39, 0x20, 0xdf, 0x97, 0x03,
	0x12, 0xb4, 0xcd, 0xf7, 0xed, 0xfe, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x46, 0x62, 0xe6,
	0x3a, 0x05, 0x00, 0x00,
}
