{
  "name": "notificationaction",
  "type": "Notificationaction",
  "description": "autogenerated",
  "__proto": {
    "package": "notification",
    "options": {
      "java_outer_classname": "NotificationApi"
    },
    "imports": [],
    "targetfile": "notification.proto"
  },
  "fields": {
    "text": {
      "description": "text of notificationaction",
      "type": "string",
      "meta": {
        "label": "notificationaction.text.id.label",
        "default": "",
        "hint": ""
      },
      "constraints": {},
      "__proto": {
        "number": 1
      }
    },
    "command": {
      "description": "command of a notificationaction",
      "type": "string",
      "meta": {
        "label": "notificationaction.command.displayName.label",
        "default": "",
        "hint": "",
        "readonly": true
      },
      "constraints": {},
      "__proto": {
        "number": 2
      }
    },
    "icon": {
      "description": "icon of a notificationaction",
      "type": "string",
      "meta": {
        "label": "notificationaction.icon.displayName.label",
        "default": "",
        "hint": "",
        "readonly": true
      },
      "constraints": {},
      "__proto": {
        "number": 3
      }
    }
  }
}
