{
  "name": "notification",
  "type": "Notification",
  "description": "autogenerated",
  "__proto": {
    "package": "notification",
    "options": {
      "java_outer_classname": "NotificationApi"
    },
    "imports": [],
    "targetfile": "notification.proto"
  },
  "fields": {
    "id": {
      "description": "Identity of notification",
      "type": "string",
      "meta": {
        "label": "notification.type.id.label",
        "default": "",
        "hint": ""
      },
      "constraints": {},
      "__proto": {
        "number": 1
      }
    },
    "display_name": {
      "description": "Localized String representation of a notification",
      "type": "string",
      "meta": {
        "label": "notification.type.displayName.label",
        "default": "",
        "hint": "",
        "readonly": true
      },
      "constraints": {},
      "__proto": {
        "number": 2
      }
    },
    "category": {
      "description": "category of a notification",
      "type": "string",
      "meta": {
        "label": "notification.type.category.label",
        "default": "",
        "hint": "",
        "readonly": true
      },
      "constraints": {},
      "__proto": {
        "number": 3
      }
    },
    "category_priority": {
      "description": "category of a notification",
      "type": "string",
      "meta": {
        "label": "notification.type.category.label",
        "default": "",
        "hint": "",
        "readonly": true
      },
      "constraints": {},
      "__proto": {
        "number": 4
      }
    },
    "message": {
      "description": "the message of a notification",
      "type": "string",
      "meta": {
        "label": "notification.type.message.label",
        "default": "",
        "hint": "",
        "readonly": true
      },
      "constraints": {},
      "__proto": {
        "number": 5
      }
    },
    "message_priority": {
      "description": "the message of a notification",
      "type": "string",
      "meta": {
        "label": "notification.type.message.label",
        "default": "",
        "hint": "",
        "readonly": true
      },
      "constraints": {},
      "__proto": {
        "number": 6
      }
    },
    "actions": {
      "description": "repeated actions",
      "type": "notification.Notificationaction",
      "meta": {
        "repeated": true
      },
      "__proto": {
        "number": 7
      }
    }
  }
}
