name: notification
type: Notification
description: autogenerated
__proto:
    package: notification
    targetfile: notification.proto
    imports: []
    options:
        java_outer_classname: NotificationApi
fields:
    id:
        type: string
        description: Identity of notification
        __proto:
            number: 1
            oneof: ""
        __ui: null
        meta:
            default: ""
            hint: ""
            label: notification.type.id.label
            options: null
            readonly: false
            repeated: false
            typespecific: null
        constraints: {}
    display_name:
        type: string
        description: Localized String representation of a notification
        __proto:
            number: 2
            oneof: ""
        __ui: null
        meta:
            default: ""
            hint: ""
            label: notification.type.displayName.label
            options: null
            readonly: true
            repeated: false
            typespecific: null
        constraints: {}
    category:
        type: string
        description: category of a notification
        __proto:
            number: 3
            oneof: ""
        __ui: null
        meta:
            default: ""
            hint: ""
            label: notification.type.category.label
            options: null
            readonly: true
            repeated: false
            typespecific: null
        constraints: {}
    category_priority:
        type: string
        description: category of a notification
        __proto:
            number: 4
            oneof: ""
        __ui: null
        meta:
            default: ""
            hint: ""
            label: notification.type.category.label
            options: null
            readonly: true
            repeated: false
            typespecific: null
        constraints: {}
    message:
        type: string
        description: the message of a notification
        __proto:
            number: 5
            oneof: ""
        __ui: null
        meta:
            default: ""
            hint: ""
            label: notification.type.message.label
            options: null
            readonly: true
            repeated: false
            typespecific: null
        constraints: {}
    message_priority:
        type: string
        description: the message of a notification
        __proto:
            number: 6
            oneof: ""
        __ui: null
        meta:
            default: ""
            hint: ""
            label: notification.type.message.label
            options: null
            readonly: true
            repeated: false
            typespecific: null
        constraints: {}
    actions:
        type: notification.Notificationaction
        description: repeated actions
        __proto:
            number: 7
            oneof: ""
        __ui: null
        meta:
            default: ""
            hint: ""
            label: ""
            options: null
            readonly: false
            repeated: true
            typespecific: null
        constraints: {}
