{
  "name": "auth",
  "type": "Auth",
  "description": "autogenerated",
  "__proto": {
    "package": "auth",
    "options": {},
    "imports": [],
    "targetfile": "auth.proto"
  },
  "fields": {
    "id": {
        "description": "Identity of Auth",
        "type": "string",
        "meta": {
          "label": "Id",
          "default": "",
          "hint": ""
        },
        "constraints": {},
        "__proto": {
          "number": 1
        }
    },
    "username": {
      "type": "string",
      "description": "The unique username, ussualy an email address",
      "meta": {
        "label": "Username",
        "hint": ""
      },
      "constraints": {},
      "__proto": {
        "number": 2
      }
    },
    "password": {
      "type": "string",
      "description": "Das _neue_ Kennwort des Benutzers",
      "meta": {
        "label": "Password",
        "hint": "Look under your keyboard"
      },
      "constraints": {
      },
      "__proto": {
        "number": 3
      }
    },
    "role": {
      "type": "string",
      "description": "",
      "meta": {
        "label": "Role",
        "hint": ""
      },
      "constraints": {
      },
      "__proto": {
        "number": 4
      }
    }

  }
}
