name: Auth
type: Auth
description: autogenerated
lifecycle: null
__proto:
    package: auth
    targetfile: auth.proto
    imports: []
    options:
        go_package: github.com/eclipse/eclipsefuro-web/furo-specs/dist/pb/auth;authpb
        java_multiple_files: "true"
        java_outer_classname: AuthProto
        java_package: com.example.tutorial.auth
fields:
    id:
        type: string
        description: Identity of Auth
        __proto:
            number: 1
        __ui: null
        meta:
            default: ""
            placeholder: ""
            hint: ""
            label: Id
            options: null
            readonly: false
            repeated: false
            typespecific: null
        constraints: {}
    username:
        type: string
        description: The unique username, ussualy an email address
        __proto:
            number: 2
        __ui: null
        meta:
            default: ""
            placeholder: ""
            hint: ""
            label: Username
            options: null
            readonly: false
            repeated: false
            typespecific: null
        constraints: {}
    password:
        type: string
        description: Das _neue_ Kennwort des Benutzers
        __proto:
            number: 3
        __ui: null
        meta:
            default: ""
            placeholder: ""
            hint: Look under your keyboard
            label: Password
            options: null
            readonly: false
            repeated: false
            typespecific: null
        constraints: {}
    role:
        type: string
        description: no description
        __proto:
            number: 4
        __ui: null
        meta:
            default: ""
            placeholder: ""
            hint: ""
            label: Role
            options: null
            readonly: false
            repeated: false
            typespecific: null
        constraints: {}
