name: Notification
type: Notification
description: autogenerated
lifecycle: null
__proto:
    package: notification
    targetfile: notification.proto
    imports: []
    options:
        go_package: github.com/eclipse/eclipsefuro-web/furo-specs/dist/pb/notification;notificationpb
        java_multiple_files: "true"
        java_outer_classname: NotificationApi
        java_package: com.example.tutorial.notification
fields:
    id:
        type: string
        description: Identity of notification
        __proto:
            number: 1
        __ui: null
        meta:
            default: ""
            placeholder: ""
            hint: ""
            label: notification.type.id.label
            options: null
            readonly: false
            repeated: false
            typespecific: null
        constraints: {}
    display_name:
        type: string
        description: Localized String representation of a notification
        __proto:
            number: 2
        __ui: null
        meta:
            default: ""
            placeholder: ""
            hint: ""
            label: notification.type.displayName.label
            options: null
            readonly: true
            repeated: false
            typespecific: null
        constraints: {}
    category:
        type: string
        description: category of a notification
        __proto:
            number: 3
        __ui: null
        meta:
            default: ""
            placeholder: ""
            hint: ""
            label: notification.type.category.label
            options: null
            readonly: true
            repeated: false
            typespecific: null
        constraints: {}
    category_priority:
        type: string
        description: category of a notification
        __proto:
            number: 4
        __ui: null
        meta:
            default: ""
            placeholder: ""
            hint: ""
            label: notification.type.category.label
            options: null
            readonly: true
            repeated: false
            typespecific: null
        constraints: {}
    message:
        type: string
        description: the message of a notification
        __proto:
            number: 5
        __ui: null
        meta:
            default: ""
            placeholder: ""
            hint: ""
            label: notification.type.message.label
            options: null
            readonly: true
            repeated: false
            typespecific: null
        constraints: {}
    message_priority:
        type: string
        description: the message of a notification
        __proto:
            number: 6
        __ui: null
        meta:
            default: ""
            placeholder: ""
            hint: ""
            label: notification.type.message.label
            options: null
            readonly: true
            repeated: false
            typespecific: null
        constraints: {}
    actions:
        type: notification.Notificationaction
        description: repeated actions
        __proto:
            number: 7
        __ui: null
        meta:
            default: ""
            placeholder: ""
            hint: ""
            label: ""
            options: null
            readonly: false
            repeated: true
            typespecific: null
        constraints: {}
