name: Notificationaction
type: Notificationaction
description: autogenerated
lifecycle: null
__proto:
    package: notification
    targetfile: notification.proto
    imports: []
    options:
        go_package: github.com/eclipse/eclipsefuro-web/furo-specs/dist/pb/notification;notificationpb
        java_multiple_files: "true"
        java_outer_classname: NotificationApi
        java_package: com.example.tutorial.notification
fields:
    text:
        type: string
        description: text of notificationaction
        __proto:
            number: 1
        __ui: null
        meta:
            default: ""
            placeholder: ""
            hint: ""
            label: notificationaction.text.id.label
            options: null
            readonly: false
            repeated: false
            typespecific: null
        constraints: {}
    command:
        type: string
        description: command of a notificationaction
        __proto:
            number: 2
        __ui: null
        meta:
            default: ""
            placeholder: ""
            hint: ""
            label: notificationaction.command.displayName.label
            options: null
            readonly: true
            repeated: false
            typespecific: null
        constraints: {}
    icon:
        type: string
        description: icon of a notificationaction
        __proto:
            number: 3
        __ui: null
        meta:
            default: ""
            placeholder: ""
            hint: ""
            label: notificationaction.icon.displayName.label
            options: null
            readonly: true
            repeated: false
            typespecific: null
        constraints: {}
