/**
 * Registry for the components which can handle a type in a specific context.
 *
 * This class is used by the furo-panel-coordinator to find the component which suites best for the given data type.
 *
 * The registry can be autogenerated from @furo/ui-builder
 *
 * ```
 * // -- register panels
 *
 * panelRegistry.registerType("auth.AuthEntity", {
 *    "edit" : "auth-auth-update-panel"
 * });
 *```
 */
export class panelRegistry {
    static registerType(type: any, panel: any): void;
    static getPanelName(type: any, suffix: any): any;
}
export namespace panelRegistry {
    const _registry: {};
}
