/**
 * Registry for the components which can handle a type in a specific context.
 *
 * This class is used by the furo-panel-coordinator to find the component which suites best for the given data type.
 *
 * The registry can be autogenerated from @furo/ui-builder
 *
 * ```
 * // -- register panels
 *
 * panelRegistry.registerType("auth.AuthEntity", {
 *    "edit" : "auth-auth-update-panel"
 * });
 *```
 */
export class panelRegistry {
  static registerType(type, panel) {
    this._registry[type] = panel;
  }

  static getPanelName(type, suffix) {
    if (suffix) {
      if (this._registry[type]) {
        return this._registry[type][suffix];
      }
      // eslint-disable-next-line no-console
      console.warn('type is not registred:', type, suffix);
      return false;
    }

    if (this._registry[type]) {
      return this._registry[type];
    }
    // eslint-disable-next-line no-console
    console.warn('type is not registred:', type);
    return false;
  }
}

panelRegistry._registry = {};
